name: Reusable Agent Runner
on:
  workflow_call:
    inputs:
      model:
        type: string
        required: false
        default: claude

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4

      - name: Echo selected model
        shell: bash
        run: echo "MODEL_PROFILE=${{ inputs.model }}"

      - name: Run orchestrator if present
        shell: bash
        run: |
          if [ -f "tools/orchestrator.ps1" ]; then
            echo "Running orchestrator..."
            pwsh -File tools/orchestrator.ps1
          else
            echo "No tools/orchestrator.ps1 found; skipping."
          fi
