name: Reusable Agent Runner

on:
  workflow_call:
    inputs:
      model:
        required: false
        type: string
        default: claude

jobs:
  run-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    env:
      MODEL_PROFILE: ${{ inputs.model }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4
        # defaults to the *calling* repo; explicit for clarity
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0

      - name: Show selected model
        shell: pwsh
        run: Write-Host "Model profile: $env:MODEL_PROFILE"

      - name: Run orchestrator stub
        shell: pwsh
        run: pwsh -File tools/orchestrator.ps1

      - name: Summarize
        shell: pwsh
        run: |
          $lines = @()
          $lines += "### MCP Sandbox Run"
          $lines += "* Repo: $env:GITHUB_REPOSITORY"
          $lines += "* Commit: $env:GITHUB_SHA"
          $lines += "* Profile: $env:MODEL_PROFILE"
          $lines -join "`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
