name: Reusable Agent Runner
on:
  workflow_call:
    inputs:
      model:
        type: string
        required: false
        default: claude

jobs:
  run-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show selected model
        shell: pwsh
        env:
          MODEL_PROFILE: ${{ inputs.model }}
        run: |
          Write-Host "Model profile: $env:MODEL_PROFILE"

      - name: Run orchestrator if present
        if: ${{ hashFiles('tools/orchestrator.ps1') != '' }}
        shell: pwsh
        env:
          MODEL_PROFILE: ${{ inputs.model }}
        run: pwsh -File tools/orchestrator.ps1
