name: Reusable Agent Runner
on:
  workflow_call:
    inputs:
      model:
        type: string
        required: false
        default: claude

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show selected model
        run: echo "Model: ${{ inputs.model }}"

      - name: Run orchestrator if present
        shell: pwsh
        run: |
          if (Test-Path "tools/orchestrator.ps1") {
            pwsh -File tools/orchestrator.ps1
          } else {
            Write-Host "No tools/orchestrator.ps1 found in caller; skipping."
          }
